on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+'
    paths:
      - '.github/workflows/**'
      - 'FiraCode.glyphs'
      - 'script/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - run: sudo apt install -y zip ttfautohint woff2 sfnt2woff-zopfli
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - if: startsWith(github.ref, 'refs/tags/')
      run: python3 ./script/update_version.py
    - run: ./script/build.sh
    - run: echo "hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - run: |
        zip -j ReFiraCode.zip \
          distr/ttf/ReFira\ Code/*.ttf \
          distr/woff/ReFira\ Code/*.woff \
          distr/woff2/ReFira\ Code/*.woff2
    - uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ReFiraCode.zip
