#
# :-S   Oh RLY? do we have to edit the build.yml AND set a git tag (label) to trigger the github build to pick up the new git tag / label?!
#

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]+.[0-9]+.*'
    paths:
      - '.github/workflows/**'
      - 'FiraCode.glyphs'
      - 'script/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: "3.x"
    - name: Install dependencies
      run: |
        pip3 install fontmake
        pip3 install ttfautohint-py
        sudo apt-get install ttfautohint
        sudo apt-get install woff2
        sudo apt-get install sfnt2woff-zopfli
        pip3 install gftools
    - if: startsWith(github.ref, 'refs/tags/')
      run: python3 ./script/update_version.py
    - run: ./script/build.sh
    - run: echo "hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@main
      with:
        name: Fira_Code_${{ env.hash }}
        path: distr
    - if: startsWith(github.ref, 'refs/tags/')
      run: python3 ./script/release.py
